name: Run (Manual)

on:
  workflow_dispatch: {}

jobs:
  run_application:
    if: github.ref_name == 'prod'
    runs-on: ubuntu-latest
    container: golang:latest
    environment: prod
    env:
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
      SHEET_NAME: ${{ secrets.SHEET_NAME }}
      GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      SEND_AS: ${{ secrets.SEND_AS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run built application
        run: go run .
